version: '3.1'

services:

  db:
    build:
      context: ./docker/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    environment:
     POSTGRES_PORT: "5432"
     POSTGRES_HOST: "db"
     CRYPT_SALT: '${CRYPT_SALT}'
     JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
     JWT_SECRET_REFRESH_KEY: '${JWT_SECRET_REFRESH_KEY}'
     TOKEN_EXPIRE_TIME: '${TOKEN_EXPIRE_TIME}'
     TOKEN_REFRESH_EXPIRE_TIME: '${TOKEN_REFRESH_EXPIRE_TIME}'
     JWT_KEY: '${JWT_KEY}'
    volumes:
      - ./src:/app/src
    ports:
       - 4000:4000