version: '3.1'

services:

  db:
    build:
      context: ./docker/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - ${POSTGRES_PORT}:5432

#  app:
 #   build:
  #    context: ./
   #   dockerfile: ./docker/app/Dockerfile
    #ports:
     # - 4000:4000