version: '3.1'

services:

  db:
    build:
      context: ./docker/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5433:5432

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 4000:4000